README recommends to set preprocessor as plugin
If it is not included it shows a warning message:
```
WARN [preprocess]: Can not load "coffee", it is not registered!
  Perhaps you are missing some plugin?
  Fatal error: undefined is not a function
```